# Generated by Django 3.1.7 on 2021-03-07 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=4)),
                ('est_income', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('budget', models.FloatField()),
                ('is_active', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetapi.budget')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetapi.envelope')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetapi.budget')),
            ],
        ),
    ]
